gsb_praticien_homepage:
    path:     /
    defaults: { _controller: GSBPraticienBundle:Home:home }

gsb_praticien_listePraticiens:
    path:     /praticiens
    defaults: { _controller: GSBPraticienBundle:Home:ListePraticiens }

gsb_praticien_listeSpecialites:
    path:     /specialites
    defaults: { _controller: GSBPraticienBundle:Home:ListeSpecialites }

gsb_praticien_listeTypePraticiens :
    path:     /typePraticiens
    defaults: { _controller: GSBPraticienBundle:Home:ListeTypePraticiens}

gsb_praticien_listeAjoutTypePraticiens :
    path: /
    defaults: { _controller: GSBPraticienBundle:Home:ListeAjoutTypePraticiens}
