gsb_praticien_homepage:
    path:     /
    defaults: { _controller: GSBPraticienBundle:Home:home }

gsb_praticien_listePraticiens:
    path:     /praticiens
    defaults: { _controller: GSBPraticienBundle:Home:ListePraticiens }

gsb_praticien_listeTypePraticiens :
    path:     /typePratiens
    defaults: { _controller: GSBPraticienBundle:Home:ListeTypePraticiens}