gsb_praticien_homepage:
    path:     /
    defaults: { _controller: GSBPraticienBundle:Home:home }

gsb_praticien_listePraticiens:
    path:     /praticiens
    defaults: { _controller: GSBPraticienBundle:Home:ListePraticiens }

gsb_praticien_listeSpecialites:
    path:     /specialites
    defaults: { _controller: GSBPraticienBundle:Home:ListeSpecialites }

gsb_praticien_listeTypePraticiens :
    path:     /typePraticiens
    defaults: { _controller: GSBPraticienBundle:Home:ListeTypePraticiens}

gsb_praticien_listeAjoutPraticiens :
    path: /ajoutPraticiens
    defaults: { _controller: GSBPraticienBundle:Home:FormAjoutPraticiens}

gsb_praticien_listeAjoutTypePraticiens :
    path: /ajoutTypePraticiens
    defaults: { _controller: GSBPraticienBundle:Home:FormAjoutTypePraticiens}

gsb_praticien_listeAjoutSpecialites :
    path: /ajoutSpecialites
    defaults: { _controller: GSBPraticienBundle:Home:FormAjoutSpecialites}

gsb_praticien_listeModifTypePraticiens :
    path: /modifTypePraticiens{id}
    defaults: { _controller: GSBPraticienBundle:Home:FormModifTypePraticiens}

gsb_praticien_supprTypePraticien :
    path : /supprimerTypePraticien/{id}
    defaults : {_controller : GSBPraticienBundle:Home:DeleteTypePraticiens}
