<?php

namespace GSB\PraticienBundle\Repository;

/**
 * type_praticienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class type_praticienRepository extends \Doctrine\ORM\EntityRepository
{
}
